### ISSUE TITLE
Writing "JavaScript Rising Stars 2017"

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/javascript-risingstars#1]
This issue tracks the different steps of the building process of "JavaScript Rising Stars 2017".

The concept is the same as last year: analyzing the trends over the last 12 months, showing both raw numbers (how many stars were added on GitHub in 2017) and providing interesting explanations

We will try to repeat the success of https://risingstars2016.js.org/. (see the story here: https://github.com/michaelrambeau/risingstars2016/issues/1)

**Comment by michaelrambeau** [comment]
## First iteration

I've built a new site with GatsbyJS, that contains both 2016 and 2017 version.
it's a multilingual site, comments will be available in English, Japanese and Chinese (and in French too, maybe).

Development version: https://risingstars.netlify.com/2017/en/ (automatically built from GitHub)

Data has been generated from `bestofjs-batches` application.
For the projects added to bestof.js.org during the year, I used this site: http://www.timqian.com/star-history/ to check how many stars the projects had at the beginning of the year.

For now, the list of tags is almost the same as last year:

* Most Popular Projects in 2017 (all categories)
* Front-end Frameworks
* Node.js Frameworks
* React Ecosystem
* Mobile
* Compilers
* Build Tools
* Testing Frameworks
* IDE
* Static Site Generators

I added 2 new categories:
* Vue Ecosystem
* CSS in JavaScript

![image](https://user-images.githubusercontent.com/5546996/34323556-b4c79fc6-e891-11e7-9fc5-32f772d1f3ac.png)


## Next steps

* Write the comments for each category, the introduction and the conclusion
* Create a new section "the stories of the year"
* Show content from _State of JavaScript_
* Improve the styling to make the 2017 page more unique, using styles similar to _State of JavaScript_ ones?

**Comment by michaelrambeau** [comment]
## Screenshots (to be included in the README.md)

### 2017 banner

![image](https://user-images.githubusercontent.com/5546996/34452534-0c525f68-ed85-11e7-8d52-647fafffea15.png)

**Comment by jhoye** [comment]
"A complete overview of the JavaScript landscape in 2017 ..." 

Do you have plans to include Ember.js?

**Comment by michaelrambeau** [comment]
@jhoye Ember did not get enough stars in 2017 (+1.2 K stars), that's why it's not in _2017 JavaScript Rising Stars_.
Check here https://bestof.js.org/tags/framework/trending/last-12-months to see the full rankings.

**Comment by Okazari** [comment]
Hey @michaelrambeau i think that adding a "Miscellaneous" category (ie: Anything that doesn't fit in any other categories) would be a great addition. As a very curious person, I would love to see that. This way it could cover a lot of things (Chatbots, Animations etc..)
WDYT ?

**Comment by michaelrambeau** [comment]
Hello @Okazari thank you for the feedback.
So this "Miscellaneous" category would cover the projects that are not among the 25 top projects overall, neither among one leaders of one of the categories.

To satisfy your curiosity, isn't it simpler to check the "Trending / 12 months" pages, from _Best of JavaScript_ application?
This way you can pick any category (or "tag") and check the 2017 leaders.

E.g. https://bestof.js.org/tags/bot/trending/last-12-months

**Comment by Okazari** [comment]
@michaelrambeau You got a point here. But i'm also lazy and would love to avoid having to check all the categories by hand. (Well i could do it, but what i want to say is that it would simpler to provide it ;) )

Btw, if you're ok with the idea, i can make a pull request.

**Comment by michaelrambeau** [comment]
@Okazari Just to understand how it would look like, how would you pick up the projects to be mentioned in the "Miscellaneous" category?
Targeting some categories and picking the project number one last year?

**Comment by Okazari** [comment]
i moved this discussion into a new issue to keep this one a little cleaner ;) (you can remove comments if you want)
