### ISSUE TITLE
Bring back the GraphQL category

### ISSUE THREAD

**Issue by mishushakov** [bestofjs/javascript-risingstars#136]
Hey team,
Looks like you removed the GraphQL category from the 2023 edition?

Being featured in the category was a great source of pride for our community (Garph) until it was suddenly removed some weeks ago 😢 

Any chance you could bring it back?

**Comment by michaelrambeau** [comment]
Hello Mish @mishushakov thank you for your interest in the project.

Sorry for the sudden change, at some point I added 3 more categories and removed the GraphQL one (see https://github.com/bestofjs/javascript-risingstars/pull/130) to keep things even.

I can bring it back, either removing one of the categories I added, or adding an extra one, have you any suggestion, just in case?

**Comment by mishushakov** [comment]
Can't speak of other categories, but it appears GraphQL has been on the list starting from the 2017 edition, not sure why drop it. Maybe you could instead merge some categories together?

**Comment by mishushakov** [comment]
At the second look though, the "charting" section looks off - let me explain why. Considering the rest of the tools in the list are **fundamental** frameworks to build JavaScript apps upon, charting is really optional.

**Comment by michaelrambeau** [comment]
OK @mishushakov thank you for the help, could you check this temporary URL:

https://javascript-risingstars-git-bring-back-graphql-category-bestofjs.vercel.app/2023/en

Also let me know if the list makes sense or if we should exclude some projects in the category for example.

**Comment by mishushakov** [comment]
Thank you so much! Love that you brought the GraphQL category back. And I'm not missing the charts category either.
CSS libraries, I'm kind of questioning (looking at the star growth), think this is falling out of fashion for things like Tailwind, Shadcn.

There's a lot of competition in Auth, ORM and JS-Runtimes right now, so maybe they would be more fitting? Or maybe a more generalised category wouldn't hurt? Here's a list of categories NPM is currently showing:

<img width="718" alt="Screenshot 2024-02-13 at 15 06 57" src="https://github.com/bestofjs/javascript-risingstars/assets/10400064/bdbd867c-7b6a-4724-9686-0f8545f3c222">

**Comment by michaelrambeau** [comment]
Thank you again @mishushakov the changes are available "in production".

About the categories, maybe we could merge CSS-in-JS and CSS libraries into a single "Styling" library and add more ones.
It's too late for the 2023 edition but everything is possible for the next edition 😄
