### ISSUE TITLE
how the /data is updated? 

### ISSUE THREAD

**Issue by sanjai0py** [bestofjs/javascript-risingstars#139]
I apologize for raising this as an issue, but I couldn't find any discussion section or Discord community for this project. I hope my message finds you well. I have a quick question regarding the project - how is the `/data` updated? 

Thank you for creating this project, and I appreciate any help you can provide.

**Comment by michaelrambeau** [comment]
Hello @sanjai0py data come from my project _Best of JS_, there is link to Discord at the top of the page, I should have put the link in _Rising Stars_ page too, sorry.

It's a bit complicated to reply how data is generated but basically I take a snapshot of the number of stars of all projects I track in Best of JS and store eveything in a database. Then, for each edition of the Rising Stars, I compute the rankings and I store the results in the `/data` folder of the Rising Stars.

**Comment by sanjai0py** [comment]
Got it! Thanks, @michaelrambeau. Your project looks awesome!
