### ISSUE TITLE
Gatsby not in GraphQL category?

### ISSUE THREAD

**Issue by SachaG** [bestofjs/javascript-risingstars#14]
Is that on purpose? Did we decide not to have the same projects appear in multiple categories?

**Comment by michaelrambeau** [comment]
Good catch, thank you Sacha, `Gatsby` was actually included in the `graphql` category, and it's the leader of the category.

![image](https://user-images.githubusercontent.com/5546996/50570150-ac78f180-0dc0-11e9-8601-df1863564e4d.png)
