### ISSUE TITLE
Japanese translations

### ISSUE THREAD

**Issue by meltedice** [bestofjs/javascript-risingstars#15]
Add your name to following lines before starting translation to avoid conflict.

コンフリクトしないように翻訳開始前に↓のリストに名前を書いてからはじめましょう。

Edit "ja.md" in each directory such as "i18n/2017/introduction/ja.md".
When you translated, and git pushed, check the corresponding checkbox.

* [x] @azukiwasher i18n/2017/introduction
* [x] @azukiwasher  i18n/2017/conclusion: 'おわりに'
* [x] @azukiwasher  i18n/2017/categories/all: '2017年人気プロジェクトランキング'
* [x] @azukiwasher  i18n/2017/categories/framework: 'フロントエンドフレームワーク'
* [x] @azukiwasher  i18n/2017/categories/nodejsframework: 'Node.jsフレームワーク'
* [x] @meltedice i18n/2017/categories/react: 'Reactボイラープレート'
* [x] @meltedice i18n/2017/categories/vue: 'Vue Ecosystem'
* [x] @azukiwasher  i18n/2017/categories/mobile: 'モバイル'
* [x] @azukiwasher  i18n/2017/categories/compiler: 'コンパイラ'
* [x] @azukiwasher  i18n/2017/categories/build: 'ビルドツール'
* [x] @meltedice i18n/2017/categories/testframework: 'テスティングフレームワーク'
* [x] @azukiwasher  i18n/2017/categories/ide: '統合開発環境（IDE）'
* [x] @azukiwasher  i18n/2017/categories/ssg: '静的サイトジェネレータ'
* [x] @azukiwasher  i18n/2017/categories/css-in-js: 'CSS in JavaScript'
* [x] @azukiwasher  i18n/2017/categories/graphql: 'GraphQL'  
* [x] @azukiwasher  i18n/2017/guests/evan: 'スペシャルゲスト'
* [x] @azukiwasher  i18n/2017/categories/misc: '番外編'
* [x] @azukiwasher  i18n/2017/common

**Comment by vanx2** [comment]
Okay, I will do "nodejsframework"

**Comment by azkwsr** [comment]
I took the liberty of picking up the followings:

- [x] [i18n/2017/introduction](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/introduction/ja.md)
- [x]  [i18n/2017/conclusion](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/conclusion/ja.md)
- [x]  [i18n/2017/categories/all](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/categories/all/ja.md)
- [x] [i18n/2017/categories/framework](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/categories/framework/ja.md)
- [x] [i18n/2017/categories/mobile](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/categories/mobile/ja.md)
- [x] [i18n/2017/categories/compiler](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/categories/compiler/ja.md)
- [x] [i18n/2017/categories/build](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/categories/build/ja.md)
- [x] [i18n/2017/categories/ssg](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/categories/ssg/ja.md)
- [x] [i18n/2017/categories/graphql](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/categories/graphql/ja.md)
- [x] [i18n/2017/categories/ide](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/categories/ide/ja.md)
- [x] [i18n/2017/guests/evan](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/guests/evan/ja.md)
- [x] [i18n/2017/categories/misc](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/categories/misc/ja.md)
- [x] [i18n/common](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/common/ja.yaml)
- [x] [i18n/categories/css-in-js](https://github.com/bestofjs/javascript-risingstars/blob/master/i18n/2017/categories/css-in-js/ja.md)


I will start working this weekend.

**Comment by michaelrambeau** [comment]
Closing the issue for the 2017 version, thank you everybody for your hard work!
