### ISSUE TITLE
No icon for Weex 

### ISSUE THREAD

**Issue by frankyxhl** [bestofjs/javascript-risingstars#17]
Weex doesn't show in current page?

Should add it into projects.json:
https://img.alicdn.com/tps/TB1zBLaPXXXXXXeXXXXXXXXXXXX-121-59.svg

**Comment by michaelrambeau** [comment]
Thank you Frank, I added `Weex` project icon.

![image](https://user-images.githubusercontent.com/5546996/34743054-bdbac102-f5cb-11e7-93bc-50e3c49e7f39.png)

**Comment by frankyxhl** [comment]
Fix confirmed. I will close this issue.
Thanks, Michael!
