### ISSUE TITLE
Missing Elm on compilers list

### ISSUE THREAD

**Issue by rogeriochaves** [bestofjs/javascript-risingstars#25]
Hey, with 4.2k starts [elm-compiler](https://github.com/elm-lang/elm-compiler) should be on the compilers list, right after Flow and before Reason

**Comment by michaelrambeau** [comment]
Hello @rogeriochaves ,
Thank you for your feedback, `Elm` project has been added to the `Compilers` category...

...but you may be disappointed, if our calculation is right, `Elm` is number 8, behind `CoffeeScript`.

![image](https://user-images.githubusercontent.com/5546996/34988614-9efb5092-fb02-11e7-88b7-27f38840ef5b.png)

**Comment by rogeriochaves** [comment]
Oh I didn't realize it was the delta of stars, makes sense, rising stars duh, thank you!
