### ISSUE TITLE
Add a "Miscellaneous" category

### ISSUE THREAD

**Issue by Okazari** [bestofjs/javascript-risingstars#26]
**Moving discussion to a new issue** 

________________

Hey @michaelrambeau i think that adding a "Miscellaneous" category (ie: Anything that doesn't fit in any other categories) would be a great addition. As a very curious person, I would love to see that. This way it could cover a lot of things (Chatbots, Animations etc..)
WDYT ?

_______________

@michaelrambeau
Hello @Okazari thank you for the feedback.
So this "Miscellaneous" category would cover the projects that are not among the 25 top projects overall, neither among one leaders of one of the categories.

To satisfy your curiosity, isn't it simpler to check the "Trending / 12 months" pages, from Best of JavaScript application?
This way you can pick any category (or "tag") and check the 2017 leaders.

E.g. https://bestof.js.org/tags/bot/trending/last-12-months

________________

@Okazari
@michaelrambeau You got a point here. But i'm also lazy and would love to avoid having to check all the categories by hand. (Well i could do it, but what i want to say is that it would simpler to provide it ;) )

Btw, if you're ok with the idea, i can make a pull request.

_____________________

@michaelrambeau
@Okazari Just to understand how it would look like, how would you pick up the projects to be mentioned in the "Miscellaneous" category?
Targeting some categories and picking the project number one last year?

**Comment by Okazari** [comment]
It would be the same logic as the 'all' category with a restriction :
They must not be included into any other categories top tiers (ie: for each `category`, not in the `category.count` bests on `category.key`)

**Comment by michaelrambeau** [comment]
OK, please go ahead if you don't mind diving in the code, I'm curious to see how it would like.

A new category called `Miscellaneous` would also mean new comments to write... in several languages! (even if we both can handle French and English versions)

And be aware that the changes would have to be approved by all other team members :)

**Comment by Okazari** [comment]
Ok, gonna give it a try and make a PR hoping for everyone approval ;) ! Thanks for your time

**Comment by Okazari** [comment]
![image](https://user-images.githubusercontent.com/5747538/34992000-edca72a2-facb-11e7-98f5-4cb1e3ca5475.png)

Here are the winners.

WDYT ?

PS : Shoudn't Yarn be in the build tool category ?

**Comment by Okazari** [comment]
And those of 2016

![image](https://user-images.githubusercontent.com/5747538/34992343-305eb690-facd-11e7-89f9-67a6e8b705bd.png)
