### ISSUE TITLE
Stories of the year

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/javascript-risingstars#3]
## Stories of the year

Collecting material from javascriptweekly.com issues in order to write the _Stories of the Year_

### Oct 2016 [305](http://javascriptweekly.com/issues/305)

[A Lawyer Analyzes Facebook's React.js License](http://www.elcaminolegal.com/single-post/2016/10/04/Facebook-Reactjs-License?utm_source=javascriptweekly&utm_medium=email)
Robert Pierce concludes React is not ‘open source.’ This spawned a large Hacker News discussion. 

### August 2017 [349](http://javascriptweekly.com/issues/349)

[Facebook Explains React's License](https://code.facebook.com/posts/112130496157735/explaining-react-s-license/)
Facebook reacts to Apache’s recent critique of React’s ‘BSD + Parents’ license by explaining how it helps them contribute to open source.

https://github.com/facebook/graphql/issues/351

https://medium.com/@reverdev/why-we-moved-from-angular-2-to-vue-js-and-why-we-didnt-choose-react-ef807d9f4163

### Sept 2017 [354](http://javascriptweekly.com/issues/354)

[Facebook Relicensing React, Jest, Flow, and Immutable.js](https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/)
Recently, there have been some [issues](https://code.facebook.com/posts/112130496157735/explaining-react-s-license/) involving patent-related features, but Facebook is now moving some of its projects to a standard MIT license.

## WebAssembly

[webpack Awarded $125,000 By Mozilla news](https://medium.com/webpack/webpack-awarded-125-000-from-moss-program-f63eeaaf4e15)
To implement first-class support for WebAssembly.

[An Abridged Cartoon Introduction To WebAssembly](https://www.smashingmagazine.com/2017/05/abridged-cartoon-introduction-webassembly/)
Lin Clark explains what exactly WebAssembly is, and what makes it fast.

[WebAssembly Will Let You Run High-Perf Apps in Your Browser story](https://spectrum.ieee.org/computing/software/webassembly-will-finally-let-you-run-highperformance-applications-in-your-browser)
A neat high level overview of WebAssembly.

> WebAssembly Will Finally Let You Run High-Performance Applications in Your Browser
> Online applications could work as smoothly as the programs you install on your machine

## Reason

[What is ReasonML?](http://2ality.com/2017/11/about-reasonml.html)

This blog post gives a brief high-level explanation of Facebook’s new programming language, ReasonML.

## Node.js evolution

* node.js now supports all major features from ES6
* `async/await` makes asynchronous programming far much easier (Nested Promise Callback Functions > Promise chains > Async Await)
* Next step: supporting `import` and `export`?

**Comment by SachaG** [comment]
How about having the "Rising Stars Awards" as one of the stories?

Could be: 

- Project of the year
- Fastest rise (if different)
- Most potential
- Best of JS's pick

**Comment by michaelrambeau** [comment]
Thank you Sacha for the good ideas.

It reminds me something I've seen on [State of JavaScript 2018](https://2018.stateofjs.com/awards/)!

![image](https://user-images.githubusercontent.com/5546996/50570179-2493e700-0dc2-11e9-9b34-d4e50b2fdd91.png)

The animation on the cards marked with the question mark was really nice!

I'd rather mention projects in the conclusion rather than picking in an official way some projects.

Just a crazy idea: since every category is an award by itself, we could make it a game, showing something like "here are the 5 nominees, pick the one you think has won the award and check if your pick was right". 

Closing this issue related to the 2017 edition, because we couldn't implement these ideas last year, but it's worth discussing it again.
