### ISSUE TITLE
is the daily data open source?

### ISSUE THREAD

**Issue by tsiq-swyx** [bestofjs/javascript-risingstars#30]
hey michael! was thinking of doing additional analysis on this data but need the daily data.. i couldnt find it here. Is it open for public view? thank you!

**Comment by michaelrambeau** [comment]
Hello @tsiq-swyx , daily data consumed by https://bestof.js.org/ is available here: 
https://bestofjs-api-v2.firebaseapp.com/projects.json

It's open for "public view" but it's not really a public API, specification may change in the future.

**Comment by tsiq-swyx** [comment]
ok fair enough. thank you!
