### ISSUE TITLE
About Secondary Use of "JavaScript Rising Stars 2017"

### ISSUE THREAD

**Issue by kazupon** [bestofjs/javascript-risingstars#31]
Hi bestofjs team!
Thank you for awesome website. ✨ 

I have a question.
Could we reuse data of this site? (and [2016](https://risingstars2016.js.org/ja/))

I'm organizer of vue.js japan users group.
Currently, We are preparing for the conference event with **non-profit** and **volunteer**.
We want to provide the docs for sponsor.

**Comment by michaelrambeau** [comment]
Hello @kazupon Kawaguchi-san!
Sorry for the late reply.
Yes, you can use data from _Rising Stars_ project, no problem!
By the way, we are in Japan too! 🇯🇵 
Let me know if you need something from us, and feel free to share any update about your event.
Thank you!

**Comment by kazupon** [comment]
@michaelrambeau 
Thanks!! ❤️ 
That's very kind of you. 
I know you live in japan.

In return, We would like to put to teaser site of Vue Conference Japan logo of bestofjs as media sponsor.
We'll publish teaser site, coming soon. 🚀 ✨ 
When we published it, I'll let you know.  😺

**Comment by kazupon** [comment]
Hi! @michaelrambeau 

We had published Vue conference teaser site.
https://vuefes.jp

We would like to put logo of bestofjs to teaser site as media sponsor. :)

**Comment by michaelrambeau** [comment]
Hello @kazupon, no problem, you can use the logo of _Best of JavaScript_ in https://vuefes.jp site.

Let me know if you need something from me, keep up the good work 😄 !

**Comment by kazupon** [comment]
Hello @michaelrambeau 
We had published sponsors on site.
https://vuefes.jp

We put logo of bestofjs to that site.
You can see it. :)

**Comment by kazupon** [comment]
Media Sponsor can attend at free (no pay ticket, one person only) for Vue Fes Conference.
We hope you attend to Vue Fes, If you are interest in it. :)

**Comment by michaelrambeau** [comment]
Hello @kazupon 

Thank you very much, I'm very proud to see _Best of JavaScript_ logo on the https://vuefes.jp homepage!

I don't think I'm available to join the event in Tokyo but let me know if there is anything I can do for you.
