### ISSUE TITLE
Show total number of stars

### ISSUE THREAD

**Issue by SachaG** [bestofjs/javascript-risingstars#4]
I feel like we should also be able to see the total number of stars. For example, it would let us see how far Vue still is from React, and estimate when it will catch up.

**Comment by michaelrambeau** [comment]
The total number of stars has been added to data (`stars` property)

```json
    {
      "name": "React",
      "url": "https://reactjs.org",
      "full_name": "facebook/react",
      "description":
        "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
      "owner_id": 69631,
      "tags": ["framework", "vdom", "react"],
      "delta": 27684,
      "stars": 84500,
      "created_at": "2013-05-24T16:15:54.000Z",
      "icon": "react.svg"
    }
```

**Comment by michaelrambeau** [comment]
4 years later (!), we show the total number of stars among project details. Everything happens!

Done here: https://github.com/bestofjs/javascript-risingstars/pull/86
