### ISSUE TITLE
JavaScript Rising Stars 2019

### ISSUE THREAD

**Issue by Chalarangelo** [bestofjs/javascript-risingstars#40]
Hello, there!

With 2020 approaching, I would like to ask if there is going to be a JavaScript Rising Stars 2019 and, if so, if the **Learning Resource** category is coming back this year. 

If you are looking for someone to write the intro for the category, I am available - I did the same last year, as I am involved in multiple projects in this category. Just let me know in advance!

Cheers!

**Comment by michaelrambeau** [comment]
Hello Angelos @Chalarangelo , it's very nice to see you again!
I think there will be a new edition of Rising Starts and yes it would be great if you could write an intro for that category (or for any category actually), thank you for offering your help!

The concept will be the same I think (unless you have an idea to improve the concept), so we already know the overall winner!
I will ping you as soon as something is set up.

**Comment by seognil** [comment]
@michaelrambeau Greeting~
And I'd like to complete the Chinese translation as last year

**Comment by michaelrambeau** [comment]
Hello @Chalarangelo  and @seognil 
I've just set up a branch called `2019` with the latest data.
... but I've not written any comment.

Temporary URL: https://2019--risingstars.netlify.com/

**Comment by michaelrambeau** [comment]
## Screenshot

To be used in the README.md

![image](https://user-images.githubusercontent.com/5546996/72196611-d39ae200-345c-11ea-9359-538c36db90b8.png)

**Comment by michaelrambeau** [comment]
Hello @Chalarangelo 
I wonder if you feel like writing some comments like you did last year?
Thank you in advance!
