### ISSUE TITLE
Angular section in Rising Stars 2019?

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/javascript-risingstars#41]
Hello Benjamin and happy new year 2020! @BBlackwo 

We plan to release the 2019 JavaScript Rising Stars (see https://github.com/bestofjs/javascript-risingstars/issues/40)

I'd like to know if you want to write about the AngularJS eco-system, like you did last year (https://github.com/bestofjs/javascript-risingstars/issues/32).

We could add credits at the end of the section, mentioning "by Benjamin Blackwood" for example.

Thank you in advance!

**Comment by BBlackwo** [comment]
Hi @michaelrambeau when do you hope to finish it this year? I'd like to be able to do it, but it depends on the timeline.

**Comment by michaelrambeau** [comment]
Thank you very much Benjamin @BBlackwo .
I don't have time to write a lot, I'd like to publish it Wednesday maybe, so that it's included in next week's "JavaScript Weekly" newsletter.
So I may leave some categories without any comment.
So just a few words from you would be great!

Just in case you missed it the temporary URL: https://2019--risingstars.netlify.com/

**Comment by BBlackwo** [comment]
Hi Michael @michaelrambeau, I'll write it up now.

**Comment by BBlackwo** [comment]
Hi Michael @michaelrambeau I just created a PR for the Angular summary and a few other small things.

I think it'd be good to add a few more Angular repos that have a lot of stars and might be in the top 10:
- `nrwl/nx`
- `angular/angularfire`
- `swimlane/ngx-charts`
- `maximegris/angular-electron`

I'm happy to add them in myself if you can point me in the direction of how to do that.

**Comment by michaelrambeau** [comment]
Thank you again Benjamin @BBlackwo ,

`ngx-charts` should definitively be tracked by _Best of JavaScript_ in the charting category.

`Nx` is already tracked, in the "monorepo" tag, it should have the "Angular" tag too, because it lets users scaffold Angular projects easily, is my understanding correct?

https://bestofjs.org/projects?tags=monorepo

I will add the 2 other projects too.

The problem is to generate data for these missing projects, it's no so simple, I will work on this point.

**Comment by BBlackwo** [comment]
Sounds good about `ngx-charts`.

I was thinking it should also have the "Angular" tag as originally it was just a monorepo tool for Angular apps. But they've expanded it recently to React and Web Components, so it might not make sense to put it in the Angular category anymore.

Cool thanks for adding those two! 👍

**Comment by michaelrambeau** [comment]
Hello again @BBlackwo 

The 3 projects you mentioned are available on _Best of JavaScript_ 

- ngx-charts
- Angular Fire
- Angular Electron

I couldn't rebuild _Rising Stars_ data to include those projects, sorry, I need more time to get the missing data.

I've merged everything: https://risingstars.js.org/2019/en/

Do you want to be introduced as a "Guest Writer" like I did for Frederic Chopin? I just need a short bio 😄 

Thank you again for your great help!

**Comment by BBlackwo** [comment]
That's great. No worries, they can be added to Rising Stars next year I guess 🙂 

Sure, I just created a PR to add me as a "Guest Writer": #48 

You're welcome!
