### ISSUE TITLE
Material-UI branding

### ISSUE THREAD

**Issue by oliviertassinari** [bestofjs/javascript-risingstars#51]
Hey, I love what you guys are doing with bestofjs :).

If you have some time, the following branding would be even better, I couldn't find where it's hosted to make a pull request, so here is it :)
```diff
-name: Material UI
-logo: https://bestofjs.org/logos/material-ui.svg
+name: Material-UI
+logo: https://avatars2.githubusercontent.com/u/33663932?s=150&v=2019
```

**Comment by oliviertassinari** [comment]
My bad, I have found the source :)

**Comment by michaelrambeau** [comment]
Hello Olivier @oliviertassinari 
Thank you for your kind words!
Could you provide a SVG file?

**Comment by oliviertassinari** [comment]
Sure, you can find it here: https://github.com/mui-org/material-ui/blob/master/docs/static/logo.svg.

**Comment by michaelrambeau** [comment]
Hello again Olivier @oliviertassinari 
I've just updated the logo in _Best of JavaScript_ (this commit: https://github.com/bestofjs/bestofjs-webui/commit/61c8fc3a6e0821e13a47b65aed581fb2052303cb), you can check the result?

#### In Best of JavaScript

https://bestofjs.org/projects?tags=component

![image](https://user-images.githubusercontent.com/5546996/72227769-a593da00-35e3-11ea-9861-dbfd379786f1.png)

#### In Rising Stars

![image](https://user-images.githubusercontent.com/5546996/72227818-310d6b00-35e4-11ea-9f08-a3afa87ad07f.png)

Merci et bonne semaine ;)

**Comment by oliviertassinari** [comment]
Awesome, thanks for taking the time. Regarding the name, is adding the `-` blocked by a technical constraint?

**Comment by michaelrambeau** [comment]
Oh sorry, no problem, it's just that I missed that point, my bad, I'm going to fix @oliviertassinari

**Comment by michaelrambeau** [comment]
@oliviertassinari _Rising Stars_ project is fixed!

![image](https://user-images.githubusercontent.com/5546996/72241070-2fb26180-3629-11ea-8fa3-3975c53427c4.png)

_Best of JavaScript_ will be rebuilt tomorrow with the right name.

**Comment by oliviertassinari** [comment]
😍
