### ISSUE TITLE
[request]: new category for code review tools

### ISSUE THREAD

**Issue by seognil** [bestofjs/javascript-risingstars#56]
Rising Stars is a ranking list, but can also as an ecosystem overview.

So, I'm thinking about tools that automating code checking, that's really important for FE dev now

e.g.

- prettier 38k stars
- eslint 17k stars
- husky 20k stars

**Comment by michaelrambeau** [comment]
Hello @seognil 
Thank you for the feedback.
All data in _Rising Stars_ project come from _Best of JS_ project.
We have already a category called "Linter": https://bestofjs.org/projects?tags=lint where you can find both _Prettier_ and _ESLint_ projects.

![image](https://user-images.githubusercontent.com/5546996/96793827-0d5f3700-1438-11eb-887a-ad4156570cb4.png)

However _Husky_ is not tracked by _Best of JS_... what would be the appropriate tags? "Git"? "Code Review" like you said?
Do you think we should create a more generic tag called "tooling"?

**Comment by seognil** [comment]
I think 'Git' is better. It's a tool for git hooks.

You reminded me that there are more for git eco sys

e.g. (which I using every day)
- <https://github.com/commitizen/cz-cli>
- <https://github.com/conventional-changelog/standard-version>

check <https://www.conventionalcommits.org/en/v1.0.0/>

---

and for npm and ci

e.g.
- <https://github.com/release-it/release-it>

**Comment by michaelrambeau** [comment]
Thank you @seognil the category "Git" will be added to _Best of JS_

About your links, do you know the difference between those 2 projects:

- https://github.com/conventional-changelog/standard-version
- https://github.com/conventional-changelog/conventional-changelog

?

Both are very popular (+ 4k stars) and seem to be able to generate Changelog files.

**Comment by seognil** [comment]
there are tons of these tools,
version bumping, changelog management, commit control, analyzing, blah blah blah
some tools may do the same things, but with different API and feature details

I haven't make a full review yet, (just picked some of them and make my workflow 'a little' better now)

**Comment by michaelrambeau** [comment]
OK thank you @seognil 
The new tag "Git" is available in _Best of JS_: https://bestofjs.org/projects?tags=git

It includes _Husky_, _Commitizen_ will be added very soon.

**Comment by michaelrambeau** [comment]
I'm closing the issue since _Commitzen_ and _Husky_ are available on _Best of JS_.
