### ISSUE TITLE
When will the rising stars for 2020 be available?

### ISSUE THREAD

**Issue by engineforce** [bestofjs/javascript-risingstars#57]

**Comment by michaelrambeau** [comment]
Hello Paul, thank you, I was waiting for someone to request it, so now we can work on that 😄 

The project is updated at the very end of the year usually.

If you can't wait, you can get an overview of the trends on _Best of JS_ where you can pick the "last 12 months" as the sort choice: https://bestofjs.org/projects?sort=yearly

**Comment by michaelrambeau** [comment]
Hello Paul @engineforce you asked for the Rising Stars? You get the Rising Stars!

There is nothing you can't get 😄 

It's live, today!
