### ISSUE TITLE
Show 20 links everywhere with "read more" after 10

### ISSUE THREAD

**Issue by SachaG** [bestofjs/javascript-risingstars#7]
I think we should harmonize the layout of each section. How about showing 10 items to begin with, and having a "show more…" link to show the next 10?

**Comment by michaelrambeau** [comment]
Sorry for the late reply @SachaG and happy new year!

I've added a "SHOW MORE" button at the end of the project list, check the result here:

https://dev--risingstars.netlify.com/2018/en/

![image](https://user-images.githubusercontent.com/5546996/50570131-fad9c080-0dbf-11e9-8d55-1ac762ceefb8.png)


About the category settings:

* `count` is the total number of items displayed in the category (50 items for the "All" category, 20, 10 or 5 depending on the categories)
* `limit` is the number of items displayed by default, before the the "SHOW MORE" button is pushed.
