### ISSUE TITLE
2020 Korean translation

### ISSUE THREAD

**Issue by melancholy14** [bestofjs/javascript-risingstars#80]
Please, add your name to the following checklist in order to avoid conflict.

- [x] @melancholy14 i18n/md/colloections/2020/ko/categories/all.md
- [x] @melancholy14 i18n/md/colloections/2020/ko/categories/angular.md
- [x] i18n/md/colloections/2020/ko/categories/build.md
- [x] i18n/md/colloections/2020/ko/categories/cssframework.md
- [x] @melancholy14 i18n/md/colloections/2020/ko/categories/framework.md
- [x] @melancholy14 i18n/md/colloections/2020/ko/categories/nodejs-framework.md
- [x] @melancholy14 i18n/md/colloections/2020/ko/categories/react.md
- [x] @melancholy14 i18n/md/colloections/2020/ko/categories/vue.md
- [x] @melancholy14 i18n/md/colloections/2020/ko/guests/atinux.md
- [x] @melancholy14 i18n/md/colloections/2020/ko/guests/bblackwo.md
- [x] @melancholy14 i18n/md/colloections/2020/ko/guests/leerob.md
- [x] @melancholy14 i18n/md/colloections/2020/ko/guests/slorber.md
- [x] @melancholy14 i18n/md/colloections/2020/ko/conclusion.md
- [x] @melancholy14 i18n/md/colloections/2020/ko/introduction.md
- [x] @melancholy14 i18n/messages/2020/ko.json
- [x] @melancholy14 i18n/messages/common/ko.json

**Comment by michaelrambeau** [comment]
Hello, sorry for the late reply!

If you'd like to work on a Korean version of the Rising Stars, I can setup a branch.

I'm closing the issue because I'm not sure about the meaning of your request but feel free to contact us if you want to work on the project.

Thank you for your understanding.

**Comment by melancholy14** [comment]
@michaelrambeau Hi, thank you for replying to my issue and sorry for making you confused.

As you guessed, it was meant to work for translating to Korean (https://github.com/melancholy14/javascript-risingstars/tree/add/korean) and also meant to show that Korean translating is in progress if someone wants to join me.

I would appreciate it if you let me know how I can work on the project.

Thanks,

**Comment by michaelrambeau** [comment]
Hello Misol @melancholy14 
Thank you for reaching us.
@rewrite0w0 already did the Korean version of the 2021 Rising Stars: https://risingstars.js.org/2021/ko
So maybe you could double check if everything is OK with the translations?

**Comment by melancholy14** [comment]
Hello @michaelrambeau 
Yes, I saw it's updated but mine is the one for the 2020 Rising Stars. (I started this work a long time ago but had been busy so I ended up finishing this recently)
Do you think it's a little bit late to add translations for 2020?
