### ISSUE TITLE
Avoid using index.js for file names

### ISSUE THREAD

**Issue by SachaG** [bestofjs/javascript-risingstars#9]
This is more of a personal preference, but I don't think we should name components `index.js`, because it makes it harder to quickly switch to them in your text editor or even do a site-wide search. 

Also we should keep naming consistent, for example `ProjectTableView` is defined as `ProjectTableView` but imported as `ProjectTable`, again making it hard to understand the code.

**Comment by michaelrambeau** [comment]
Alright, no problem at all, I will fix the names every time I work on these files.

Of course feel free to rename the files you are working on, too.

**Comment by SachaG** [comment]
I'll let you rename them all at once to avoid too many git conflicts.
