### ISSUE TITLE
Suggestion for new category: "Database libraries"

### ISSUE THREAD

**Issue by nikolasburk** [bestofjs/javascript-risingstars#91]
While they're a crucial part of most applications, database libraries (ORMS, query builders, ...) don't get much attention in the Node.js ecosystem. I would suggest to maybe introduce a new category that would include these libraries and also solve the issue that Prisma is mis-categorized in the "GraphQL"-category. 

Note that Prisma 1 indeed used to be a "GraphQL generator" but Prisma 2 (now 3) is purely a DB access library.

**Comment by michaelrambeau** [comment]
Hello Nikolas @nikolasburk 
Thank you for reaching us.
Actually _Rising Stars_ is a kind of subset of _Best of JS_, a snapshot we make every year enhanced by some writings.
We pick and aggregate tags from _Best of JS_ to create the categories displayed in the _Rising Stars_
So if you check _Best of JS_ you will see that Prisma is also classified as an "ORM":

https://bestofjs.org/projects?tags=orm

![image](https://user-images.githubusercontent.com/5546996/148189062-1b5a73ed-c05c-4911-bbca-889896bfe3c1.png)


I'm aware that ORM is not exactly the same thing as a "database library" but it's often associated.
Is the tagging correct, except GraphQL?
If yes, I can re-generate data  and Prisma would be removed from the page.

Thank you for your understanding, tagging is really a difficult task (but that's maybe what makes _Best of JS_ valuable).

**Comment by nikolasburk** [comment]
Thank you so much for the quick reply and the explanation, that makes a lot of sense!

Actually I think the tagging looks great, as long as it contains "ORM" we should be fine! 🙂  

Prisma does have some benefits (e.g. an integrated dataloader) when used to build a GraphQL API, so having the "GraphQL"-tag _in addition_ to the others is still helpful IMO. If you're not responsible for the categories yourself, then never mind this issue 😄

**Comment by michaelrambeau** [comment]
Sorry Nikolas @nikolasburk for the misunderstanding,  I am responsible for the category as I have created both _Best of JS_ and the _Rising Stars_, so anything is possible, don't give up!

From what you have said, it makes sense to have the tag `GraphQL` associated to _Prisma_ project.

About the tagging, I forgot to mention you can see it right from the _Rising Stars_ rankings, when clicking on the project row to see the details, but maybe it's not enough obvious?

![image](https://user-images.githubusercontent.com/5546996/148211378-d773e071-8be8-4fdf-9eb6-bc84c877202f.png)

We could show the tags directly under the project description maybe but it would add a lot of clutter to the UI, I think.

About your initial question, we could have a category "DB library / ORM" but it's a very specific domain, so I'm not sure if it fits the concept of the _Rising Stars_.

Let me know if you have any idea to improve things, thank you again for your cooperation!
